services:

  db:
    image: go-auth-auth-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"