service:
  user:
    server:
      host: 127.0.0.1
      port: 5431
      timeout: 5
    DB:
      host: 127.0.0.1
      port: 5440
      timeout: 5

  auth:
    server:
      host: 127.0.0.1
      port: 5433
      timeout: 6
