services:

  db:
    image: go-auth-user-db
    restart: always
    container_name: user-db
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - ./db/.env
    ports:
      - "${DB_PORT}:5432"