services:

  db:
    image: go-auth-user-db
    restart: always
    container_name: user-db
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    env_file:
      - ./db/.env
    ports:
      - "${DB_PORT}:5432"